export enum AuthActionTypes {
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  UPDATE_ACCOUNT_ID = "UPDATE_ACCOUNT_ID",
  UPDATE_MERCHANT_CENTER_ID = "UPDATE_MERCHANT_CENTER_ID",
  SET_LISTING_SCOPE_DATA = "SET_LISTING_SCOPE_DATA",
}
